### PR TITLE
Create selectable Action Cards and Group

### PR DESCRIPTION
**Pull request by GailWilson**
- Create `ActionCard` & `ActionCardGroup` -- following the example of `ActionSelectorGroup`
- Create `Pill` to support the pill showing the image/member count

@carlosdp let me know if the card props are generic enough, too generic or whatnot and if i set this up properly.

Nits on the image that I know are wrong:
- icon is off
- typography sizing & top icon sizing looks weird

## Screenshot
Screen Shot 2021-12-27 at 4 36 22 PM

### CODE REVIEW

**Review by gentianmetaphor — CHANGES_REQUESTED** [review]
The pill grey is 'default_light'. Checking the subline test is 'secondary_black'? Couldn't quite tell. BTW- the elements tab in Figma has the right values but some of the screens don't because I created them before the components.

**Review by carlosdp — APPROVED** [review]
looks good! I did a merge commit to remove the `dist/` stuff since I changed how that works in master

**Comment by carlosdp** [comment]
oh shoot, I merged before realizing @gentianmetaphor had comments, sorry! just address them in a separate PR lol

**Comment by GailWilson** [comment]
@gentianmetaphor GREAT EYE!!!

@carlosdp can you link the PR here or in the other PR to link these?

**Pull request merged**
